// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGTwbq947eZiw0TIdNgTGJuulYoYVu-o',
    appId: '1:333783990965:web:b019e2522a4af4580234fc',
    messagingSenderId: '333783990965',
    projectId: 'pushnotification-75e9f',
    authDomain: 'pushnotification-75e9f.firebaseapp.com',
    storageBucket: 'pushnotification-75e9f.appspot.com',
    measurementId: 'G-MK3PX1C0Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtjTTCAe7WYqSeHDz5NfqEXbhuIzGBDUQ',
    appId: '1:333783990965:android:1f879b1ca52da0ab0234fc',
    messagingSenderId: '333783990965',
    projectId: 'pushnotification-75e9f',
    storageBucket: 'pushnotification-75e9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOau52htx2xptqty0zAN4_3mAeGtW_im0',
    appId: '1:333783990965:ios:88c6799f274b3b710234fc',
    messagingSenderId: '333783990965',
    projectId: 'pushnotification-75e9f',
    storageBucket: 'pushnotification-75e9f.appspot.com',
    iosClientId: '333783990965-a3qk7hb3decbqlmsatjafgbhuj0hbme2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOau52htx2xptqty0zAN4_3mAeGtW_im0',
    appId: '1:333783990965:ios:88c6799f274b3b710234fc',
    messagingSenderId: '333783990965',
    projectId: 'pushnotification-75e9f',
    storageBucket: 'pushnotification-75e9f.appspot.com',
    iosClientId: '333783990965-a3qk7hb3decbqlmsatjafgbhuj0hbme2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationApp',
  );
}
